# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en

# Import global cspell configuration
import:
  - ~/.cspell.json

# Additional words specific to nvim config
words:
  - Autocmds
  - augroup
  - autoread
  - bufhidden
  - buflisted
  - cmdheight
  - cmdline
  - Cmdline
  - COLORTERM
  - completeopt
  - copen
  - cterm
  - ctermbg
  - ctermfg
  - cursorline
  - cword
  - expandtab
  - fnamemodify
  - formatoptions
  - getcharstr
  - getcwd
  - globalstatus
  - guibg
  - guifg
  - guisp
  - histadd
  - histget
  - hlsearch
  - ignorecase
  - jumplist
  - keymaps
  - lastused
  - lazypath
  - linewise
  - lnum
  - lspinfo
  - mapleader
  - menuone
  - netrw
  - newtopline
  - nohlsearch
  - noinsert
  - noselect
  - shiftwidth
  - shortmess
  - showmode
  - smarttab
  - softtabstop
  - startuptime
  - statusline
  - stdpath
  - swapfile
  - systemlist
  - tabline
  - termguicolors
  - truecolor
  - undofile
  - unnamedplus
  - vimdoc
  - vimgrep
  - Virt
  - whichwrap
  - winbar
  - winsaveview
  - writting
  - aibou
  - andymass
  - autopairs
  - autotag
  - bashls
  - busa
  - devicons
  - dstein
  - edgemotion
  - folke
  - gitsigns
  - Gitsigns
  - goacf
  - Goacf
  - gobf
  - Gobf
  - Gobfop
  - Gocd
  - goolord
  - gopr
  - Gopr
  - haya
  - hlchunk
  - hlslens
  - Hlslens
  - hrsh
  - jsonls
  - kevinhwang
  - linediff
  - Linediff
  - lspconfig
  - lspkind
  - luacheckrc
  - lualine
  - luarc
  - lukas
  - Maan
  - machakann
  - nacro
  - nvimtools
  - onsails
  - petertriho
  - psql
  - quickhl
  - Radev
  - rainbowhxch
  - reineke
  - Rethy
  - shfmt
  - smartword
  - smoka
  - startify
  - stylua
  - tzachar
  - williamboman
  - windwp
  - yamlls
  - yutkat
